## Pytorch


##  Introduction

### Matrices

We have **Matrices** in Numpy
and similar to that we have **Tensors** in Pytorch

In [10]:
arr = [[1,2,3],[4,5,6]]
arr

[[1, 2, 3], [4, 5, 6]]

In [11]:
np.array(arr)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
torch.Tensor(arr)


 1  2  3
 4  5  6
[torch.FloatTensor of size 2x3]

In [14]:
#initialize

np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [15]:
torch.ones((2,3))


 1  1  1
 1  1  1
[torch.FloatTensor of size 2x3]

In [16]:
# Random values

np.random.rand(2,3)

array([[ 0.40791492,  0.42713508,  0.09077352],
       [ 0.95713505,  0.24941506,  0.49152105]])

In [17]:
torch.rand(4,4)


 0.8261  0.2923  0.3483  0.5429
 0.2296  0.0140  0.1119  0.2340
 0.1307  0.1271  0.8649  0.9055
 0.2980  0.0192  0.3826  0.3824
[torch.FloatTensor of size 4x4]

In [ ]:
# Seeds

np.seed(0)
np.random.rand()